# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 21:44
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('amount_available', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Available Amount')),
                ('amount_ledger', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Ledger Amount')),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'asset'), (2, 'liability'), (3, 'equity')])),
                ('currency', models.CharField(default='EUR', max_length=12, verbose_name='Currency')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'authorisation', b'authorisation'), (b'presentment', b'presentment')], max_length=12, verbose_name='Message_types')),
                ('card_id', models.CharField(max_length=8, verbose_name='Card ID')),
                ('transaction_id', models.CharField(max_length=12, verbose_name='Scheme Ttransaction ID')),
                ('merchant_name', models.CharField(max_length=128, verbose_name='Merchant Name')),
                ('merchant_country', models.CharField(max_length=4, verbose_name='Merchant Country')),
                ('merchant_mcc', models.SmallIntegerField(verbose_name='Merchant Category Code')),
                ('merchant_city', models.CharField(help_text='City of merchant', max_length=64, null=True)),
                ('billing_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Billing amount')),
                ('billing_currency', models.CharField(max_length=12, verbose_name='Billing Currency')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Transaction amount')),
                ('transaction_currency', models.CharField(max_length=12, verbose_name='Transaction Currency')),
                ('settlement_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Settlement amount')),
                ('settlement_currency', models.CharField(max_length=12, null=True, verbose_name='Settlement Currency')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Scheme Message',
                'verbose_name_plural': 'Scheme Messages',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('external_transaction_id', models.CharField(max_length=12, null=True, verbose_name='Scheme transaction id')),
                ('status', models.SmallIntegerField(choices=[(-1, 'Canceled'), (0, 'Drafted'), (1, 'Processed')], verbose_name='Transfer Status')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='issuer.Account')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='issuer.Transaction', verbose_name='Transactions')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
            },
        ),
        migrations.AlterUniqueTogether(
            name='schememessage',
            unique_together=set([('type', 'transaction_id')]),
        ),
    ]
